num = int(input("Digite um número de 1 a 10: "))
# Multiplicação
print(f"\n{num} x 1 = {num*1}")
print(f"{num} x 2 = {num*2}")
print(f"{num} x 3 = {num*3}")
print(f"{num} x 4 = {num*4}")
print(f"{num} x 5 = {num*5}")
print(f"{num} x 6 = {num*6}")
print(f"{num} x 7 = {num*7}")
print(f"{num} x 8 = {num*8}")
print(f"{num} x 9 = {num*9}")
print(f"{num} x 10 = {num*10}")
# Divisão
print(f"\n{num} ÷ 1 = {num/1:.2f}")
print(f"{num} ÷ 2 = {num/2:.2f}")
print(f"{num} ÷ 3 = {num/3:.2f}")
print(f"{num} ÷ 4 = {num/4:.2f}")
print(f"{num} ÷ 5 = {num/5:.2f}")
print(f"{num} ÷ 6 = {num/6:.2f}")
print(f"{num} ÷ 7 = {num/7:.2f}")
print(f"{num} ÷ 8 = {num/8:.2f}")
print(f"{num} ÷ 9 = {num/9:.2f}")
print(f"{num} ÷ 10 = {num/10:.2f}")
# Adição
print(f"\n{num} + 1 = {num+1}")
print(f"{num} + 2 = {num+2}")
print(f"{num} + 3 = {num+3}")
print(f"{num} + 4 = {num+4}")
print(f"{num} + 5 = {num+5}")
print(f"{num} + 6 = {num+6}")
print(f"{num} + 7 = {num+7}")
print(f"{num} + 8 = {num+8}")
print(f"{num} + 9 = {num+9}")
print(f"{num} + 10 = {num+10}")
# Subtração
print(f"\n{num} - 1 = {num-1}")
print(f"{num} - 2 = {num-2}")
print(f"{num} - 3 = {num-3}")
print(f"{num} - 4 = {num-4}")
print(f"{num} - 5 = {num-5}")
print(f"{num} - 6 = {num-6}")
print(f"{num} - 7 = {num-7}")
print(f"{num} - 8 = {num-8}")
print(f"{num} - 9 = {num-9}")
print(f"{num} - 10 = {num-10}")

