nome_completo = input("Digite seu nome completo: ")
idade = int(input("Digite sua idade:"))
endereco = input("Digite seu endereço:")
profissao = input("Digite sua profissao:")
print("\nCadastro:")
print(f"Nome completo: {nome_completo}")
print(f"Idade: {idade} anos")
print(f"Endereço: {endereco}")
print(f"Profissão: {profissao}")
